- tap_postgres/__init__.py
Sends JSON and JSONB column types as objects and not as STRINGS.
This makes possible loading JSONs into VARIANT (recommended for snowflake) or can flatten the JSONs optionally (not really recommended).
> Send JSON and JSONB columns as objects

- tap_postgres/sync_strategies/logical_replication.py
Since we consume the wal2json messages differently than the original stitch/singer tap, does it make sense to rename the slot name as well avoiding collision with the other tap?
> Renamed logical replication slot prefix

- tap_postgres/sync_strategies/logical_replication.py
previous output
`
{
"type": "STATE",
"value": {
"bookmarks": {
"postgres_source_db-logical1-logical1_table1": {
"last_replication_method": "LOG_BASED",
"lsn": 25346960,
"version": 1569418760524,
"xmin": null
},
"postgres_source_db-logical1-logical1_table2": {
"last_replication_method": "LOG_BASED",
"lsn": 25347344,
"version": 1569418760548,
"xmin": null
},
"postgres_source_db-logical2-logical2_table1": {
"last_replication_method": "LOG_BASED",
"lsn": 1,
"version": 1569418760563,
"xmin": null
}
},
"currently_syncing": null
}
}
`
new output
`
{
"type": "STATE",
"value": {
"bookmarks": {
"postgres_source_db-logical1-logical1_table1": {
"last_replication_method": "LOG_BASED",
"lsn": 25347344,
"version": 1569418760524,
"xmin": null
},
"postgres_source_db-logical1-logical1_table2": { …
> Update singer streams to lsn_last_processed before emiting STATE message

- setup.py
- tap_postgres/__init__.py
- tap_postgres/sync_strategies/logical_replication.py
- create ability to set break_at_end_lsn
- create ability to set max_run_seconds
- only send feedback when lsn_comitted has increased
- remove some incompatible singer tap-postgres code
- bump version
> make break_at_end_lsn optional

- sample_logging.conf
- setup.py
- tap_postgres/__init__.py
- tap_postgres/db.py
- tap_postgres/sync_strategies/full_table.py
- tap_postgres/sync_strategies/incremental.py
- tap_postgres/sync_strategies/logical_replication.py
Switch to pipelinewise-singer-python to be able to customize logging.
If `LOGGING_CONF_FILE` env variable points to a logging file like this:
```
[loggers]
keys=root
[handlers]
keys=stderr
[formatters]
keys=child
[logger_root]
level=INFO
handlers=stderr
formatter=child
propagate=0
[handler_stderr]
level=INFO
class=StreamHandler
formatter=child
args=(sys.stderr,)
[formatter_child]
class=logging.Formatter
format=time=%(asctime)s name=%(name)s level=%(levelname)s message=%(message)s
datefmt=%Y-%m-%d %H:%M:%S
```
Then the logs would look like this
```
time=2020-02-06 17:31:03 name=tap_postgres level=INFO message=Selected streams: ['public-test_table'] 
time=2020-02-06 17:31:03 name=tap_postgres level=INFO message=end_lsn = 26690208 
time=2020-02-06 17:31:03 name=tap_postgres level=INFO …
```
> [AP-473] Refactor logging

- .circleci/config.yml
- .gitignore
- .noserc
- setup.py
- tap_postgres/__init__.py
- tap_postgres/sync_strategies/logical_replication.py
- tests/test_discovery.py
- tests/test_full_table_interruption.py
- tests/test_unsupported_pk.py
This PR is to enable run existing automated tests in circleci.
It's using Postgres 11.4 in docker to run test cases.
The current test coverage is 49% which should be improved, especially for the logical_replication.py but adding more targeted test cases will be addressed in separated PRs:
> [AP-651] Enable and fix tests in circleci

- tap_postgres/sync_strategies/logical_replication.py
- tests/test_logical_replication.py
This PR fixes an issue when `LOG_BASED` method can't extract data from tables with space in the name.
This is due to a specific string escape method required by wal2json plugin. More info about the correct formatting at https://github.com/eulerto/wal2json/blob/master/README.md#parameters  wal2json escape strings in the `filter-tables` and `add-tables` section.
> [AP-659] Fix extracting data from tables with space in the name

- tap_postgres/__init__.py
- tap_postgres/sync_strategies/logical_replication.py
- tests/test_logical_replication.py
This PR makes possible to `LOG_BASE` replicate multiple database in the same postgres instance by multiple parallel running taps.
**Changes**
* Discovering only the database that provided in the `config.json`. Replicating multiple databases requires multiple taps.
* Generating unique replication slot names dynamically
* Removed the `filter_dbs` optional parameter
* Test cases
* Docstrings in new functions
* Fixing some identations
> [AP-655] Handle to LOG_BASED replicate muliple databases by multiple taps

- tap_postgres/sync_strategies/logical_replication.py
- tests/test_logical_replication.py
Replication slot naming pattern is about to change starting from PPW 0.16.0 to allow log based replication from the same database by multiple taps. The naming patterns:
```
<PPW 0.16.0: pipelinewise_<dbname>
>=PPW 0.16.0: pipelinewise_<dbname>_<tap_id>
```
At the same time we don't want to reconfigure all the existing taps and re-create the replication slots when upgrading the PPW. Instead of this the tap should find the old replication slot with the old name if exists and should keep using it.
This logic was implemented in the fastsync by https://github.com/transferwise/pipelinewise/pull/388 but the similar change not added here to tap-postgres
> [AP-655] Fixed an issue when existing replication slot not found

- tap_postgres/db.py
- tests/test_db.py
Fixed an issue when `JSON` type not converted to python dictionary and the value passed as string in the singer output message. The conversion was working only for `JSONB` but not for `JSON`.
This PR adds some additional tests for other data type conversions.
> [AP-700] Fixed issue when JSON type not converted to dictionary

- tap_postgres/sync_strategies/logical_replication.py
- tests/test_logical_replication.py
When using logical replication from a Postgres tap, Pipelinewise generates the name of the Postgres replication slot used from a combination of prefix, database name, and tap name. This does not work if any of the constituent parts contain characters that are not valid in Postgres replication slot names, or if the full generated name is more than 64 characters long.
Replace invalid characters with an underscore and truncate the generated name at 64 characters. See https://github.com/transferwise/pipelinewise/issues/529. [A similar PR ](https://github.com/transferwise/pipelinewise/pull/530)has been opened in the main repo for the fast sync.
https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1401189673/Change+Classifications+and+Expectations) Label (`change:standard`, …
>  [FIX] - Ensure generated Postgres replication slot name is valid

- .circleci/config.yml
- Makefile
- tap_postgres/db.py
- tap_postgres/sync_strategies/full_table.py
- tap_postgres/sync_strategies/incremental.py
- tap_postgres/sync_strategies/logical_replication.py
- tests/test_db.py
- tests/test_full_table_interruption.py
- tests/test_logical_replication.py
Timestamps, with or without tz, in the source can either have era in them, e.g `BC` , or the year could be in the far far future > `9999`.
All replication methods fail or produce invalid stream when fetching such timestamps.
Consider the following table
```
CREATE TABLE "order"
(
id serial primary key,
cvarchar varchar,
created_at timestamp default current_timestamp,
updated_at timestamp with time zone
);
```
Let's insert this row:
```
insert into "order" (cvarchar, updated_at)
values ('X', '0001-12-31 23:40:28+00 BC')
;
```
Both incremental and full table fail with
```
ValueError: year 0 is out of range
```
Let's insert this row:
```
insert into "order" (cvarchar, updated_at)
values ('X','15000-12-31 23:40:28+00'')
```
Incremental yield this record stream
```
{"type": "RECORD", "stream": …
```
> [AP-369] Handle timestamps out of range

- tap_postgres/db.py
* SSL connections to Postgres are supported but not configured on DB connection.
* This is based on [this upstream tap PR ](https://github.com/singer-io/tap-postgres/pull/80)
* [Slack conversation](https://singer-io.slack.com/archives/CNL7DL597/p1600352090056300?thread_ts=1600346910.052800&cid=CNL7DL597)
* "ssl: true" needs to be added to db_conn in the tap's YAML for this to work
* SSL config is now set in db.py's open_connection
https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1401189673/Change+Classifications+and+Expectations) Label (`change:standard`, `change:impactful`, `change:emergency`)
> Enable SSL

- tap_postgres/db.py
CircleCI is currently failing with a pylint error:
```
#!/bin/bash -eo pipefail
. ./virtualenvs/tap-postgres/bin/activate
pylint --rcfile .pylintrc --disable duplicate-code tap_postgres/
************* Module tap_postgres.db
tap_postgres/db.py:57:0: C0303: Trailing whitespace (trailing-whitespace)
-----------------------------------
Your code has been rated at 9.99/10
```
This PR is removing a whitespace.
> Make pylint happy

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/QUESTION.md
- .github/ISSUE_TEMPLATE/config.yml
No github templates in this repo and new issues and PRs pop up the not applicable default TW template.
Adding github templates:
* Pull Request template
* Issue templates:
- 3 issue types, (bug, feature request and question), 
- Issues are automatically labelled to make further issue analysis easier.
- TW default template to **Report a security vulnerability**, that is required for every public, open source TransferWise project. You can find an example [here](https://github.com/transferwise/pipelinewise-tap-google-analytics/security/policy). This should be available in every public repo.
- Link to the community slack channel for open discussion
This PR makes the issues page to look like this when somebody raises an issue:
> Github templates

- setup.py
- tap_postgres/sync_strategies/logical_replication.py
Dependabot is about to upgrade pylint 2.4.4 to 2.6.0 in [this PR](https://github.com/transferwise/pipelinewise-tap-postgres/pull/75) but the new pylint gives error:
```
tap_postgres/sync_strategies/logical_replication.py:595:8: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
```
Bump pylint and fix pylint error
> Bump pylint from 2.4.4 to 2.6.0

- tap_postgres/db.py
- tests/test_db.py
The code that put bounds on timestamps wrongly treats timestamp arrays
as timestamps and crashes.
This change excludes arrays from that behaviour, though we should probably
also bound the timestamps inside the array in the same way.
> Avoid processing timestamp arrays as timestamps

- tap_postgres/sync_strategies/logical_replication.py
- tests/test_logical_replication.py
Fixes https://github.com/transferwise/pipelinewise-tap-postgres/issues/119 (exception thrown if date column value has a date with year > 9999). 
Set any date past 9999-12-31 to 9999-12-31 and log a warning message.
> Handle dates with year > 9999

- tap_postgres/sync_strategies/logical_replication.py
See https://github.com/transferwise/pipelinewise-tap-postgres/issues/133
`max_run_seconds` does not work as intended because it is wrapped within another contradictory condition.
> Remove `max_run_seconds` dependency on msg

- .github/workflows/ci.yaml
- Makefile
- README.md
- docker-compose.yml
- tap_postgres/__init__.py
- tap_postgres/db.py
- tap_postgres/sync_strategies/logical_replication.py
- tests/test_discovery.py
- tests/test_full_table_interruption.py
- tests/utils.py
Alternate implementation of #131. I'm not sure how to go about testing this without setting up quite a lot of additional infrastructure. Do you think this needs additional testing?
> Add `use_secondary` config flag

- tap_postgres/__init__.py
tap-postgres doesn't abort the running query when the tap is terminated
add signal handler to abort the running query when the tap is terminated
> AP-1207 - abort query on tap termination

- CHANGELOG.md
- setup.py
- tap_postgres/sync_strategies/incremental.py
PostgreSQL does not make efficient use of _datetime_ index only scans when performing a large select as done by the INCREMENTAL replication method
Wrap INCREMENTAL query in a SELECT * sub-query to speed up data retrieval
So instead of
```
SELECT  "colour" , "id" , "name"
FROM "public"."COW"
WHERE  "id"  >= '3'::integer
ORDER BY  "id"  ASC
```
use
```
SELECT  "colour" , "id" , "name" 
FROM (
SELECT *
FROM "public"."COW"
WHERE  "id"  >= '3'::integer
ORDER BY  "id"  ASC
) pg_speedup_trick
```
this will significantly speed up queries on _datetime_ indexes, but queries on _int_ columns are not negatively impacted
> Wrap INCREMENTAL query in a SELECT * sub-query to speed up data retrieval

- tap_postgres/sync_strategies/incremental.py
> Fix missing ORDER BY statement during first incremental sync

- README.md
- tap_postgres/__init__.py
- tap_postgres/sync_strategies/incremental.py
- tests/unit/test_incremental.py
When running incremental sync on busy tables, the query will run for hours or days which causes issues on the database side, as it interferes with things like vacuuming.
To avoid making any sweeping changes on the incremental logic, I suggest introducing an optional `limit` config which would be added to every single incremental query to limit how many rows the query returns thus limit its runtime too.
> AP-1424: limit config to mitigate long running incremental queries
